/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConnectionCode = IDL.Text;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Attachment = IDL.Record({
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'avatar' : IDL.Opt(Attachment),
});
export const ConversationId = IDL.Nat;
export const MessageId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Message = IDL.Record({
  'id' : MessageId,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'sender' : UserId,
  'conversationId' : ConversationId,
  'attachments' : IDL.Vec(Attachment),
});
export const MessagePage = IDL.Record({
  'messages' : IDL.Vec(Message),
  'nextCursor' : IDL.Opt(MessageId),
});
export const ChatError = IDL.Variant({
  'alreadyUsedCode' : IDL.Null,
  'notParticipant' : IDL.Null,
  'cannotConnectToSelf' : IDL.Null,
  'expiredCode' : IDL.Null,
  'invalidCode' : IDL.Null,
  'alreadyConnected' : IDL.Null,
  'conversationNotFound' : IDL.Null,
  'emptyMessage' : IDL.Null,
});
export const ConversationSummary = IDL.Record({
  'id' : ConversationId,
  'participants' : IDL.Vec(UserId),
  'lastMessageAt' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'unreadCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConnectionCode' : IDL.Func([], [ConnectionCode], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func(
      [ConversationId, IDL.Opt(MessageId), IDL.Nat],
      [IDL.Variant({ 'ok' : MessagePage, 'err' : ChatError })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveConversation' : IDL.Func(
      [ConversationId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : ChatError })],
      [],
    ),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'markConversationRead' : IDL.Func(
      [ConversationId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : ChatError })],
      [],
    ),
  'redeemConnectionCode' : IDL.Func(
      [ConnectionCode],
      [IDL.Variant({ 'ok' : ConversationId, 'err' : ChatError })],
      [],
    ),
  'saveCallerProfile' : IDL.Func([UserProfile], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendMessage' : IDL.Func(
      [ConversationId, IDL.Text, IDL.Vec(Attachment)],
      [IDL.Variant({ 'ok' : Message, 'err' : ChatError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConnectionCode = IDL.Text;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Attachment = IDL.Record({
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'avatar' : IDL.Opt(Attachment),
  });
  const ConversationId = IDL.Nat;
  const MessageId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Message = IDL.Record({
    'id' : MessageId,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'sender' : UserId,
    'conversationId' : ConversationId,
    'attachments' : IDL.Vec(Attachment),
  });
  const MessagePage = IDL.Record({
    'messages' : IDL.Vec(Message),
    'nextCursor' : IDL.Opt(MessageId),
  });
  const ChatError = IDL.Variant({
    'alreadyUsedCode' : IDL.Null,
    'notParticipant' : IDL.Null,
    'cannotConnectToSelf' : IDL.Null,
    'expiredCode' : IDL.Null,
    'invalidCode' : IDL.Null,
    'alreadyConnected' : IDL.Null,
    'conversationNotFound' : IDL.Null,
    'emptyMessage' : IDL.Null,
  });
  const ConversationSummary = IDL.Record({
    'id' : ConversationId,
    'participants' : IDL.Vec(UserId),
    'lastMessageAt' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'unreadCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConnectionCode' : IDL.Func([], [ConnectionCode], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func(
        [ConversationId, IDL.Opt(MessageId), IDL.Nat],
        [IDL.Variant({ 'ok' : MessagePage, 'err' : ChatError })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveConversation' : IDL.Func(
        [ConversationId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : ChatError })],
        [],
      ),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'markConversationRead' : IDL.Func(
        [ConversationId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : ChatError })],
        [],
      ),
    'redeemConnectionCode' : IDL.Func(
        [ConnectionCode],
        [IDL.Variant({ 'ok' : ConversationId, 'err' : ChatError })],
        [],
      ),
    'saveCallerProfile' : IDL.Func([UserProfile], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendMessage' : IDL.Func(
        [ConversationId, IDL.Text, IDL.Vec(Attachment)],
        [IDL.Variant({ 'ok' : Message, 'err' : ChatError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };