/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attachment {
  'blob' : ExternalBlob,
  'name' : string,
  'size' : bigint,
  'mimeType' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export type ChatError = { 'alreadyUsedCode' : null } |
  { 'notParticipant' : null } |
  { 'cannotConnectToSelf' : null } |
  { 'expiredCode' : null } |
  { 'invalidCode' : null } |
  { 'alreadyConnected' : null } |
  { 'conversationNotFound' : null } |
  { 'emptyMessage' : null };
export type ConnectionCode = string;
export type ConversationId = bigint;
export interface ConversationSummary {
  'id' : ConversationId,
  'participants' : Array<UserId>,
  'lastMessageAt' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'unreadCount' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : MessageId,
  'createdAt' : Timestamp,
  'text' : string,
  'sender' : UserId,
  'conversationId' : ConversationId,
  'attachments' : Array<Attachment>,
}
export type MessageId = bigint;
export interface MessagePage {
  'messages' : Array<Message>,
  'nextCursor' : [] | [MessageId],
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'displayName' : string,
  'avatar' : [] | [Attachment],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a new short, shareable connection code for the caller.
   */
  'createConnectionCode' : ActorMethod<[], ConnectionCode>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown documentation of the backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Read the caller's own profile, if one has been saved.
   */
  'getCallerProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch a page of messages, newest-first, using an optional cursor.
   */
  'getMessages' : ActorMethod<
    [ConversationId, [] | [MessageId], bigint],
    { 'ok' : MessagePage } |
      { 'err' : ChatError }
  >,
  /**
   * / Read another user's public profile.
   */
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Leave/end a conversation for the caller.
   */
  'leaveConversation' : ActorMethod<
    [ConversationId],
    { 'ok' : null } |
      { 'err' : ChatError }
  >,
  /**
   * / List the caller's active connections with unread counts.
   */
  'listConversations' : ActorMethod<[], Array<ConversationSummary>>,
  /**
   * / Mark all messages in a conversation as read for the caller.
   */
  'markConversationRead' : ActorMethod<
    [ConversationId],
    { 'ok' : null } |
      { 'err' : ChatError }
  >,
  /**
   * / Redeem a friend's connection code, opening a shared conversation.
   */
  'redeemConnectionCode' : ActorMethod<
    [ConnectionCode],
    { 'ok' : ConversationId } |
      { 'err' : ChatError }
  >,
  /**
   * / Create or replace the caller's profile (display name and avatar).
   */
  'saveCallerProfile' : ActorMethod<[UserProfile], undefined>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Send a text and/or attachment message to a conversation.
   */
  'sendMessage' : ActorMethod<
    [ConversationId, string, Array<Attachment>],
    { 'ok' : Message } |
      { 'err' : ChatError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];